<?php
/**
 * Defines
 */
define('RENT_CARS_SETTINGS_FRONT_THEME', 'rent_cars');

/**
 * Implements hook_init().
 */
function rent_cars_settings_init() {
  global $theme_key;

  if ($theme_key == RENT_CARS_SETTINGS_FRONT_THEME && drupal_is_front_page()) {
    drupal_add_library('rent_cars_settings', 'nivo_slider');
    drupal_add_js(drupal_get_path('module', 'rent_cars_settings') . '/js/rent_cars_settings_nivo_slider.js');
  }
/*  drupal_add_library('drupal_way', 'jquery_localscroll');
  drupal_add_library('drupal_way', 'jquery_scrollto');
  drupal_add_library('drupal_way', 'fancybox');
  drupal_add_library('system', 'ui.accordion');*/
  //drupal_add_library('system', 'effects.highlight');
}

/**
 * Implements hook_library().
 */
function rent_cars_settings_library() {
  $nivo_slider_path = libraries_get_path('nivo_slider');
  $libraries['nivo_slider'] = array(
    'title' => 'Nivo Slider',
    'website' => 'https://github.com/gilbitron/Nivo-Slider',
    'version' => '3.2',
    'js' => array(
      $nivo_slider_path . '/jquery.nivo.slider.pack.js' => array(),
    ),
    'css' => array(
      $nivo_slider_path . '/nivo-slider.css' => array(),
      $nivo_slider_path . '/themes/default/default.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'jquery'),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_preprocess_html().
 */
function rent_cars_settings_preprocess_html(&$variable) {
  $variable['classes_array'] = array_merge($variable['classes_array'], $variable['user']->roles);
  if (!in_array('authenticated user', $variable['user']->roles) && arg(0) == 'cart') {
    rent_cars_settings_redirect_anonymous();
  }
}

/**
 * Implements hook_preprocess_page().
 */
function rent_cars_settings_preprocess_page(&$variable) {
  //dsm($variable);
}

/**
 * Implements hook_preprocess_node().
 */
function rent_cars_settings_preprocess_node(&$variable) {
  $variable['theme_hook_suggestions'][] = 'node__' . $variable['type'] . '__' . $variable['view_mode'];
  if ($variable['node']->type == 'product') {
    drupal_add_library('rent_cars_settings', 'nivo_slider');
    drupal_add_js(drupal_get_path('module', 'rent_cars_settings') . '/js/rent_cars_settings_nivo_slider.js');
   // $variable['title'] = 'qsqs';
    //dsm($variable);
  }
}

/**
 * Implements hook_preprocess_field().
 */
function rent_cars_settings_preprocess_field(&$variable) {
  $variable['theme_hook_suggestions'][] = 'field__' . $variable['element']['#field_name'] . '__' . $variable['element']['#bundle'] . '__' . $variable['element']['#view_mode'];
  //dsm($variable['theme_hook_suggestions']);
  //dsm($variable);
}

/**
 * Implements hook_form_alter().
 */
function rent_cars_settings_form_alter(&$form, &$form_state, $form_id) {
  if (preg_match('/commerce_cart_add_to_cart_form_/', $form_id)) {
    global $user;

    if (!in_array('authenticated user', $user->roles)) {
      $form['#submit'] = array('rent_cars_settings_redirect_anonymous');
    }
    $form['quantity']['#title'] = t('Day');
    $form['quantity']['#title_display'] = 'after';
  }
  if ($form_id == 'commerce_order_ui_order_form') {

  }
  if ($form_id == 'search_api_ranges_block_slider_view_form_field_product_products:commerce_price:amount_decimal') {
    unset($form['text-range']);
    $form['reset'] = array(
      '#type' => 'submit',
      '#name' => 'reset',
      '#value' => t('Reset'),
      '#submit' => array('rent_cars_settings_form_search_api_ranges_submit'),
      '#attributes' => array('class' => array('rent-cars-reset-prise')),
    );
  }
}

/**
 *
 */
function rent_cars_settings_gallery($results = NULL) {
  $output = '';
  if (!empty($results)) {
    foreach ($results as $result) {
      if (isset($result->_field_data['nid']['entity'])) {
        $output .= '<div id="' . $result->_field_data['nid']['entity']->type . '-' .  $result->_field_data['nid']['entity']->nid . '" class="nivo-html-caption">';
      }
      if (isset($result->field_body[0]['rendered']['#markup'])) {
        $output .= $result->field_body[0]['rendered']['#markup'];
      }
      if (isset($result->_field_data['nid']['entity']) && isset($result->field_body[0]['rendered']['#markup'])) {
        $output .= '</div>';
      }
    }
  }
  return $output;
}

/**
 * @param null $node
 * @param null $field
 * @param null $image_style
 * @return bool|string
 */
function rent_cars_settings_im_create_url($node = NULL, $field = NULL, $image_style = NULL) {

  if (!empty($node) && !empty($field) && !empty($image_style)) {

    $field_image = field_get_items('node', $node, $field);
    $derivative_uri = '';

    if (isset($field_image[0]['uri'])) {
      $derivative_uri = image_style_path($image_style, $field_image[0]['uri']);
      $image_style_source = image_style_load($image_style);

      if (!file_exists($derivative_uri) && $image_style_source) {
        image_style_create_derivative($image_style_source, $field_image[0]['uri'], $derivative_uri);
      }
    }

    return file_create_url($derivative_uri);
  }
  return '';
}

function rent_cars_settings_get_field_value($node = NULL, $field = NULL) {
  if (!empty($node) && !empty($field) && !empty($image_style)) {
    $field_values = field_get_items('node', $node, $field);
    if (isset($field_values[0]['value'])) {
      return $field_values[0]['value'];
    }
  }
  return '';
}

function rent_cars_settings_redirect_anonymous() {
  drupal_set_message(t('Before booking a car You need <a href="/user">login</a> or <a href="/user/register">sign up</a>'));
  drupal_goto('user');
}

function rent_cars_settings_form_search_api_ranges_submit($form, &$form_state) {
  drupal_goto('cars');
}
