<?php
/**
 * Defines
 */
define('RENT_CARS_SETTINGS', 'rent_cars');
/*$menu = menu_tree_output(menu_tree_all_data('main-menu'));
print drupal_render($menu);*/
/**
 * Implements hook_init().
 */
function rent_cars_settings_init() {
  global $base_url, $theme_key;

  if ($theme_key == RENT_CARS_SETTINGS && drupal_is_front_page()) {
    drupal_add_library('rent_cars_settings', 'nivo_slider');
    drupal_add_js(drupal_get_path('module', 'rent_cars_settings') . '/js/rent_cars_settings_nivo_slider.js');
  }
/*  drupal_add_library('drupal_way', 'jquery_localscroll');
  drupal_add_library('drupal_way', 'jquery_scrollto');
  drupal_add_library('drupal_way', 'fancybox');
  drupal_add_library('system', 'ui.accordion');*/
  //drupal_add_library('system', 'effects.highlight');
}

/**
 * Implements hook_library().
 */
function rent_cars_settings_library() {
  $nivo_slider_path = libraries_get_path('nivo_slider');
  $libraries['nivo_slider'] = array(
    'title' => 'Nivo Slider',
    'website' => 'https://github.com/gilbitron/Nivo-Slider',
    'version' => '3.2',
    'js' => array(
      $nivo_slider_path . '/jquery.nivo.slider.pack.js' => array(),
    ),
    'css' => array(
      $nivo_slider_path . '/nivo-slider.css' => array(),
      $nivo_slider_path . '/themes/default/default.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'jquery'),
    ),
  );

  return $libraries;
}

/**
 *
 */
function rent_cars_settings_gallery($results = NULL) {
  $output = '';
  if (!empty($results)) {
    foreach ($results as $result) {
      if (isset($result->_field_data['nid']['entity'])) {
        $output .= '<div id="' . $result->_field_data['nid']['entity']->type . '-' .  $result->_field_data['nid']['entity']->nid . '" class="nivo-html-caption">';
      }
      if (isset($result->field_body[0]['rendered']['#markup'])) {
        $output .= $result->field_body[0]['rendered']['#markup'];
      }
      if (isset($result->_field_data['nid']['entity']) && isset($result->field_body[0]['rendered']['#markup'])) {
        $output .= '</div>';
      }
    }
  }
  return $output;
}

/**
 * @param null $node
 * @param null $field
 * @param null $image_style
 * @return bool|string
 */
function rent_cars_settings_im_create_url($node = NULL, $field = NULL, $image_style = NULL) {

  if (!empty($node) && !empty($field) && !empty($image_style)) {

    $field_image = field_get_items('node', $node, $field);
    $derivative_uri = '';

    if (isset($field_image[0]['uri'])) {
      $derivative_uri = image_style_path($image_style, $field_image[0]['uri']);
      $image_style_source = image_style_load($image_style);

      if (!file_exists($derivative_uri) && $image_style_source) {
        image_style_create_derivative($image_style_source, $field_image[0]['uri'], $derivative_uri);
      }
    }

    return file_create_url($derivative_uri);
  }
  return '';
}

function rent_cars_settings_get_field_value($node = NULL, $field = NULL) {
  if (!empty($node) && !empty($field) && !empty($image_style)) {
    $field_values = field_get_items('node', $node, $field);
    if (isset($field_values[0]['value'])) {
      return $field_values[0]['value'];
    }
  }
  return '';
}
